apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: benchmark-spark1
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: swr.cn-north-4.myhuaweicloud.com/yunjisuanpro/pyspark-douban:v11
  mainApplicationFile: "local:///opt/spark/work-dir/benchmark.py"
  arguments:
    - "spark"
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreRequest: "500m"
    memory: "512m"
    memoryOverhead: "128m"
    serviceAccount: spark
  executor:
    cores: 1
    coreRequest: "500m"
    instances: 1
    memory: "512m"
    memoryOverhead: "128m"